// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1SDDqxThr3dzNbwkVeB9Z38AeblSCDhs',
    appId: '1:390243723337:web:c373eacc278c05a7cab798',
    messagingSenderId: '390243723337',
    projectId: 'parkingsystem-17803',
    authDomain: 'parkingsystem-17803.firebaseapp.com',
    storageBucket: 'parkingsystem-17803.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB89biKjteInMkLrzL-y0K9q66K91hK2T0',
    appId: '1:390243723337:android:1b687348e7d1f2a4cab798',
    messagingSenderId: '390243723337',
    projectId: 'parkingsystem-17803',
    storageBucket: 'parkingsystem-17803.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKDbiMoDKzEryCxwk9fu-M0UWKFX8LhWI',
    appId: '1:390243723337:ios:cc6b1567f994dd07cab798',
    messagingSenderId: '390243723337',
    projectId: 'parkingsystem-17803',
    storageBucket: 'parkingsystem-17803.firebasestorage.app',
    iosBundleId: 'com.example.parkingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKDbiMoDKzEryCxwk9fu-M0UWKFX8LhWI',
    appId: '1:390243723337:ios:cc6b1567f994dd07cab798',
    messagingSenderId: '390243723337',
    projectId: 'parkingsystem-17803',
    storageBucket: 'parkingsystem-17803.firebasestorage.app',
    iosBundleId: 'com.example.parkingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD1SDDqxThr3dzNbwkVeB9Z38AeblSCDhs',
    appId: '1:390243723337:web:668f33be1c836caacab798',
    messagingSenderId: '390243723337',
    projectId: 'parkingsystem-17803',
    authDomain: 'parkingsystem-17803.firebaseapp.com',
    storageBucket: 'parkingsystem-17803.firebasestorage.app',
  );
}
